version: "3.9"

services:
  sdk:
    container_name: sdk
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - ./:/app
    working_dir: /app
    command: tail -f /dev/null
    environment:
      - GRADLE_USER_HOME=/app/.gradle
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_CREDENCIAL_USERNAME=${SMTP_CREDENCIAL_USERNAME}
      - SMTP_CREDENCIAL_PASSWORD=${SMTP_CREDENCIAL_PASSWORD}
  db:
    image: mysql:8.0.29
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    volumes:
      - ./docker/db/data:/var/lib/mysql