version: "3.9"

services:
  sdk:
    container_name: sdk
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - ./:/app
    working_dir: /app
    command: tail -f /dev/null